/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pak;

/**
 *
 * @author PC
 */
public class CashierInterfaceMain extends javax.swing.JFrame {

    /**
     * Creates new form CashierInterfaceMain
     */
    public CashierInterfaceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabelProductCode = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        EasySari = new javax.swing.JLabel();
        TableScrollpane = new javax.swing.JScrollPane();
        Plist = new javax.swing.JTable();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelProductList = new javax.swing.JLabel();
        jTextFieldProductCode = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelNamePrice = new javax.swing.JLabel();
        jLabelTotalAmount = new javax.swing.JLabel();
        jTextFieldTotalAmount = new javax.swing.JTextField();
        jButtonEndTransact = new javax.swing.JButton();
        jLabelAmountReceived = new javax.swing.JLabel();
        jTextFieldAmountRecieved = new javax.swing.JTextField();
        jLabelChange = new javax.swing.JLabel();
        jTextFieldChange = new javax.swing.JTextField();
        jButtonPrintReceipt = new javax.swing.JButton();
        jLabelPurchase = new javax.swing.JLabel();
        jButtonTotal = new javax.swing.JButton();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuOther = new javax.swing.JMenu();
        jMenuStockMonitor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));
        MainPanel.setToolTipText("");

        jLabelProductCode.setBackground(new java.awt.Color(0, 0, 0));
        jLabelProductCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelProductCode.setText("Product Code");

        jPanelHeader.setBackground(new java.awt.Color(153, 153, 153));

        EasySari.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        EasySari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EasySari.setText("EasySari");
        EasySari.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(551, 551, 551)
                .addComponent(EasySari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EasySari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        EasySari.getAccessibleContext().setAccessibleDescription("");

        Plist.setAutoCreateRowSorter(true);
        Plist.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Plist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Description", "Quantity", "Price"
            }
        ));
        TableScrollpane.setViewportView(Plist);

        jLabelQuantity.setBackground(new java.awt.Color(0, 0, 0));
        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelQuantity.setText("Quantity");

        jLabelProductList.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelProductList.setText("Product List");

        jTextFieldProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductCodeActionPerformed(evt);
            }
        });

        jTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityActionPerformed(evt);
            }
        });

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabelNamePrice.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNamePrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNamePrice.setText("Price (Per Piece)");

        jLabelTotalAmount.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTotalAmount.setText("  TOTAL");

        jTextFieldTotalAmount.setEditable(false);
        jTextFieldTotalAmount.setAutoscrolls(false);
        jTextFieldTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalAmountActionPerformed(evt);
            }
        });

        jButtonEndTransact.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonEndTransact.setText("End Transaction");
        jButtonEndTransact.setToolTipText("");
        jButtonEndTransact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndTransactActionPerformed(evt);
            }
        });

        jLabelAmountReceived.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAmountReceived.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAmountReceived.setText("Amount Received");

        jTextFieldAmountRecieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountRecievedActionPerformed(evt);
            }
        });

        jLabelChange.setBackground(new java.awt.Color(0, 0, 0));
        jLabelChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChange.setText("Change");

        jTextFieldChange.setEditable(false);
        jTextFieldChange.setAutoscrolls(false);
        jTextFieldChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChangeActionPerformed(evt);
            }
        });

        jButtonPrintReceipt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonPrintReceipt.setText("Print Receipt");
        jButtonPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintReceiptActionPerformed(evt);
            }
        });

        jLabelPurchase.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelPurchase.setText("Purchase");

        jButtonTotal.setText("Total");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                .addComponent(jLabelTotalAmount)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTotalAmount))
                            .addComponent(TableScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelChange)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                            .addComponent(jTextFieldAmountRecieved, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(76, 76, 76))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(MainPanelLayout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelProductCode)
                                                        .addComponent(jLabelAmountReceived)))
                                                .addComponent(jButtonPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(55, 55, 55)))
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)))
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelQuantity)
                                    .addComponent(jTextFieldQuantity)
                                    .addComponent(jButtonEndTransact, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jButtonTotal))))
                            .addComponent(jTextFieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNamePrice)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabelProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addComponent(jLabelPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(969, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TableScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantity)
                            .addComponent(jLabelProductCode))
                        .addGap(4, 4, 4)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNamePrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTotal))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAmountReceived)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAmountRecieved, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotalAmount)
                    .addComponent(jButtonPrintReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEndTransact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenuOther.setText("Other");

        jMenuStockMonitor.setText("Stock Monitoring");
        jMenuStockMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStockMonitorActionPerformed(evt);
            }
        });
        jMenuOther.add(jMenuStockMonitor);

        jMenuBarMain.add(jMenuOther);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void jTextFieldProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductCodeActionPerformed

    private void jTextFieldTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountActionPerformed

    private void jTextFieldAmountRecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountRecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountRecievedActionPerformed

    private void jTextFieldChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChangeActionPerformed

    private void jButtonEndTransactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndTransactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEndTransactActionPerformed

    private void jButtonPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrintReceiptActionPerformed

    private void jMenuStockMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStockMonitorActionPerformed
        // TODO add your handling code here:
        CashierAddandStockMonitoring stockFrame = new CashierAddandStockMonitoring();
        stockFrame.setVisible(true);
        
        this.dispose();
        
        // Optionally hide this frame:
        // this.setVisible(false);
    }//GEN-LAST:event_jMenuStockMonitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierInterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierInterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierInterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierInterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierInterfaceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EasySari;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable Plist;
    private javax.swing.JScrollPane TableScrollpane;
    private javax.swing.JButton jButtonEndTransact;
    private javax.swing.JButton jButtonPrintReceipt;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JLabel jLabelAmountReceived;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JLabel jLabelNamePrice;
    private javax.swing.JLabel jLabelProductCode;
    private javax.swing.JLabel jLabelProductList;
    private javax.swing.JLabel jLabelPurchase;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuOther;
    private javax.swing.JMenuItem jMenuStockMonitor;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jTextFieldAmountRecieved;
    private javax.swing.JTextField jTextFieldChange;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldProductCode;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldTotalAmount;
    // End of variables declaration//GEN-END:variables
}
